### ISSUE TITLE
Add a small padding/margin at the top of editor window

### ISSUE THREAD

**Issue by b4stien** [kenwheeler/broceanic-theme#2]
![screen shot 2015-11-20 at 11 39 12](https://cloud.githubusercontent.com/assets/1778107/11297845/60096576-8f7b-11e5-9942-d7ed396a7ee5.png)

As you can see in the attached screenshot the first line of a file is super close to the top bar, would it be possible to add some space over there?

**Comment by zpnk** [comment]
@b4stien Try increasing your line padding settings in preferences.

I was only able to duplicate your screenshot by setting a negative top padding (-2):
![screen shot 2016-04-08 at 12 08 58 pm](https://cloud.githubusercontent.com/assets/3493970/14394773/c65f32cc-fd82-11e5-817f-f7d9a42e9712.png)

But here's how it looks with top and bottom padding set to 1:
![screen shot 2016-04-08 at 12 09 18 pm](https://cloud.githubusercontent.com/assets/3493970/14394775/cb42e98c-fd82-11e5-8ce8-94e9d2f32b54.png)

Add this to your Preferences.sublime-settings to try:

``` json
"line_padding_bottom": 1,
"line_padding_top": 1,
```
